(program
    (= GRID_SIZE 50)
    ; Clicking on active object rotates it. Clicking on inactive object activates it and deactivates previously active one. 
    (object BigTriangle (: color String) (: m Bool) (: angle Number) (: active Bool) (list 
        (Cell 0 -1 color) (Cell 0 0 color)
        (Cell 1 -2 color) (Cell 1 -1 color) (Cell 1 0 color) (Cell 1 1 color)
        (Cell 2 -3 color) (Cell 2 -2 color) (Cell 2 -1 color) (Cell 2 0 color) (Cell 2 1 color) (Cell 2 2 color)
        (Cell 3 -4 color) (Cell 3 -3 color) (Cell 3 -2 color) (Cell 3 -1 color) (Cell 3 0 color) (Cell 3 1 color) (Cell 3 2 color) (Cell 3 3 color)
        (Cell 4 -5 color) (Cell 4 -4 color) (Cell 4 -3 color) (Cell 4 -2 color) (Cell 4 -1 color) (Cell 4 0 color) (Cell 4 1 color) (Cell 4 2 color) (Cell 4 3 color) (Cell 4 4 color)        
        (Cell 5 -6 color) (Cell 5 -5 color) (Cell 5 -4 color) (Cell 5 -3 color) (Cell 5 -2 color) (Cell 5 -1 color) (Cell 5 0 color) (Cell 5 1 color) (Cell 5 2 color) (Cell 5 3 color) (Cell 5 4 color) (Cell 5 5 color)        
    ))
    (object SmallTriangle (: color String) (: m Bool) (: angle Number) (: active Bool) (list
        (Cell 0 0 color)
        (Cell 1 -1 color) (Cell 1 0 color) (Cell 1 1 color)
        (Cell 2 -2 color) (Cell 2 -1 color) (Cell 2 0 color) (Cell 2 1 color) (Cell 2 2 color)))
    (object Square (: color String) (: m Bool) (: angle Number) (: active Bool) (list
        (Cell -1 -1 color) (Cell -1 0 color) (Cell -1 1 color)
        (Cell 0 -1 color) (Cell 0 0 color) (Cell 0 1 color)
        (Cell 1 -1 color) (Cell 1 0 color) (Cell 1 1 color)))
    (object Parallelogram (: color String) (: m Bool) (: angle Number) (: active Bool) (list
        (Cell -1 -2 color) (Cell 0 -1 color) (Cell 1 0 color)
        (Cell -1 -1 color) (Cell 0 0 color) (Cell 1 1 color)
        (Cell -1 0 color) (Cell 0 1 color) (Cell 1 2 color)
        (Cell -1 1 color) (Cell 0 2 color) (Cell 1 3 color)
        (Cell -1 2 color) (Cell 0 3 color) (Cell 1 4 color)
        (Cell -1 3 color) (Cell 0 4 color) (Cell 1 5 color)
        ))
    (object MediumTriangle (: color String) (: m Bool) (: angle Number) (: active Bool) (list
        (Cell 0 0 color) (Cell 0 1 color) (Cell 0 2 color) (Cell 0 3 color) (Cell 0 4 color) (Cell 0 5 color)
        (Cell 1 0 color) (Cell 1 1 color) (Cell 1 2 color) (Cell 1 3 color) (Cell 1 4 color) 
        (Cell 2 0 color) (Cell 2 1 color) (Cell 2 2 color) (Cell 2 3 color) 
        (Cell 3 0 color) (Cell 3 1 color) (Cell 3 2 color) 
        (Cell 4 0 color) (Cell 4 1 color) 
        (Cell 5 0 color)
        ))

    (: shape1 BigTriangle)
    (= shape1 (initnext (BigTriangle "red" true 0 true (Position 1 10)) (prev shape1)))
    (: shape2 BigTriangle)
    (= shape2 (initnext (BigTriangle "blue" true 0 true (Position 8 10)) (prev shape2)))
    (: shape3 SmallTriangle)
    (= shape3 (initnext (SmallTriangle "green" true 0 true (Position 15 10)) (prev shape3)))
    (: shape4 Square)
    (= shape4 (initnext (Square "yellow" true 0 true (Position 20 10)) (prev shape4)))
    (: shape5 Parallelogram)
    (= shape5 (initnext (Parallelogram "purple" true 0 true (Position 27 10)) (prev shape5)))
    (: shape6 MediumTriangle)
    (= shape6 (initnext (MediumTriangle "orange" true 0 true (Position 34 10)) (prev shape6)))
    (: shape7 SmallTriangle)
    (= shape7 (initnext (SmallTriangle "pink" true 0 true (Position 41 10)) (prev shape7)))

    (: active_shape String)
    (= active_shape "shape1")

    (on ((left)) (= active_shape (moveLeftNoCollision active_shape)))
    (on ((right)) (= active_shape (moveRightNoCollision active_shape)))
    (on ((up)) (= active_shape (moveUpNoCollision active_shape)))
    (on ((down)) (= active_shape (moveDownNoCollision active_shape)))
)
