site_name:        Autumn.jl
repo_url:         https://github.com/riadas/Autumn.jl
site_description: Autumn is a library for causal and probabilistic inference in Julia.
site_author:      zenna, riadas

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
